stages:
    - build
    - publish

build gitlab-ci:
    stage: build
    image:
        name: gcr.io/kaniko-project/executor:debug
        entrypoint: [""]
    script:
        - mkdir -p /kaniko/.docker
        - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
        - /kaniko/executor
          --context $CI_PROJECT_DIR
          --dockerfile $CI_PROJECT_DIR/Dockerfile
          --destination $CI_REGISTRY_IMAGE/cloudflare-cname-switcher:$CI_COMMIT_SHORT_SHA

publish gitlab-ci:
    stage: publish
    image:
        name: gcr.io/go-containerregistry/crane:debug
        entrypoint: [""]
    script:
        - crane auth login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
        - crane tag "$CI_REGISTRY_IMAGE/cloudflare-cname-switcher:$CI_COMMIT_SHORT_SHA" "v2"
    only:
        - main

publish docker-hub:
    stage: publish
    image:
        name: gcr.io/go-containerregistry/crane:debug
        entrypoint: [""]
    script:
        - crane auth login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
        - crane auth login -u "${DHUB_REGISTRY_USER}" -p "${DHUB_REGISTRY_PASSWORD}" "${DHUB_REGISTRY}"
        - crane copy "$CI_REGISTRY_IMAGE/cloudflare-cname-switcher:$CI_COMMIT_SHORT_SHA" "$DHUB_REGISTRY_IMAGE/cloudflare-cname-switcher:v2"
    only:
        - main

publish github-ghcr:
    stage: publish
    image:
        name: gcr.io/go-containerregistry/crane:debug
        entrypoint: [""]
    script:
        - crane auth login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" "${CI_REGISTRY}"
        - crane auth login -u "${GHCR_REGISTRY_USER}" -p "${GHCR_REGISTRY_PASSWORD}" "${GHCR_REGISTRY}"
        - crane copy "$CI_REGISTRY_IMAGE/cloudflare-cname-switcher:$CI_COMMIT_SHORT_SHA" "$GHCR_REGISTRY_IMAGE/cloudflare-cname-switcher:v2"
    only:
        - main
