[package]
name = "cloudflare-cname-switcher"
version = "2.1.6"
edition = "2021"

[dependencies]
yaml-rust2 = "0.9.0"
hyper = { version = "1.4.1", features = ["client", "http1", "server"] }
tokio = { version = "1.40.0", features = ["full"] }
notify = "7.0.0"
prometheus = "0.13.4"
rustdns = "0.4.0"
rand = "0.8.5"
env_logger = "0.11.5"
log = "0.4.20"
hyper-util = { version = "0.1.9", features = ["tokio"] }
http-body-util = "0.1.2"
bytes = "1.7.2"
tokio-rustls = "0.26.0"
webpki-roots = "0.26.6"
rustls-pki-types = "1.9.0"
serde = "1.0.210"
serde_json = "1.0.128"
chrono = "0.4.38"
itertools = "0.13.0"
