record: "_backend.example.com" # this record will by updated to point to the healthy endpoint(s)
endpoints: # a list of endpoints to monitor / fallback to
  - dns:
      record: "_service1.example.com"
      ttl: 60 # this is the TTL of the record(s), if this endpoint is selected
      resolver: 1.1.1.1
    monitoring:
      uri: "http://service1.example.com/healthz" # must respond with 200, maybe with SSL/TLS
      interval: 30 # in seconds
      confidence: 3 # amount of successful checks needed, until we switch (back)
      marker: null # string required to be present in the response body
    sticky_duration: null # in seconds, how long to keep this endpoint selected, even if not primary anymore
    weight: 10 # lower is higher priority
  - dns:
      record: "_service2.example.com"
      ttl: 300 # recommended: let clients stick longer to the secondary endpoint during and after a failover
      resolver: 1.1.1.1
    monitoring: null
    sticky_duration: null
    weight: 20
cloudflare:
  token: token # Cloudflare account -> API-Token -> create a new one with the Zone.DNS permission
  zone_id: 123456abcdef # available in the Cloudflare dashboard
telegram: # optional, set to null to disable
  token: token # set the bot token
  chat_id: 123456978 # set the chat/channel/group id
